# Generated by Django 3.0.3 on 2020-02-23 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWithPrivacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.PositiveIntegerField()),
                ('field', models.CharField(max_length=255, verbose_name='campo')),
                ('processed_image', models.ImageField(upload_to='', verbose_name='imagem processada')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='criado em')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_with_privacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_type', 'instance_id', 'field')},
            },
        ),
    ]
