# Generated by Django 3.0.2 on 2020-01-29 03:11

import django.core.validators
from django.db import migrations, models
import dual_rocks.authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='at',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\.\\_\\-]{3,16}$', 'Utilize apenas letras (A-Z), . (ponto), _ (underline) e/ou - (hífen). Com no mínimo 3 caracteres e no máximo 16.'), dual_rocks.authentication.models.ForbiddenValuesValidator(['admin', 'login', 'logout', 'register'], 'Você não pode usar "%(value)s" como @.')], verbose_name='@'),
        ),
    ]
