# Generated by Django 3.0.2 on 2020-02-05 17:14

import django.core.validators
from django.db import migrations, models
import dual_rocks.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture_crop_data',
            field=models.TextField(blank=True, null=True, verbose_name='dados de corte da foto'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='at',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\.\\_\\-]{3,16}$', 'Utilize apenas letras (A-Z), . (ponto), _ (underline) e/ou - (hífen). Com no mínimo 3 caracteres e no máximo 16.'), dual_rocks.validators.ForbiddenValuesValidator(['admin', 'login', 'logout', 'register', 'profiles'], 'Você não pode usar "%(value)s" como @.')], verbose_name='@'),
        ),
    ]
