# Generated by Django 3.0.3 on 2020-02-19 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0004_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-published_at']},
        ),
        migrations.CreateModel(
            name='UserViewPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_image', models.ImageField(upload_to='', verbose_name='imagem processada')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='criado em')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='user_profile.Photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
