# Generated by Django 3.0.3 on 2020-02-19 03:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0005_auto_20200219_0001'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userviewphoto',
            unique_together={('user', 'photo')},
        ),
    ]
